"""Adicionando pizzas com chave estrangeira para categoria

Revision ID: 848183aedd74
Revises: 74051705c2ff
Create Date: 2024-12-03 20:19:35.642716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848183aedd74'
down_revision = '74051705c2ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sabor', sa.String(length=80), nullable=True),
    sa.Column('ingredientes', sa.String(length=280), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pizza')
    # ### end Alembic commands ###
